name: Publish to npm on Tag

on:
  push:
    tags:
      - 'v*' # Matches tags that start with 'v', e.g., v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or your desired Node.js version
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build # If you have a build process
      
      - name: Set npm registry
        run: yarn config set registry https://registry.npmjs.org/

      - name: Publish to NPM
        run: yarn publish packages/docusaurus-ai
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}